apiVersion: v2
name: prometheus
description: Prometheus component for Karavel
type: application
version: 0.1.0
appVersion: 2.28.0
maintainers:
  - name: MatteoJoliveau
    email: matteo.joliveau@mikamai.com

home: https://prometheus.io/
sources:
  - https://github.com/prometheus-operator/kube-prometheus
  - https://github.com/projectkaravel/platform

annotations:
  karavel.io/dependencies: grafana
