apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "external-dns.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "external-dns.labels" . | nindent 4 }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      {{- include "external-dns.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "external-dns.labels" . | nindent 8 }}
      {{- with .Values.route53.iamRole }}
      annotations:
        iam.amazonaws.com/role: {{ . }}
      {{- end}}
    spec:
      serviceAccountName: external-dns
      containers:
        - name: external-dns
          image: k8s.gcr.io/external-dns/external-dns:v{{.Chart.AppVersion}}
          args:
            - --source=service
            - --source=ingress
            {{- with .Values.domainFilter }}
            - --domain-filter={{ . }} # will make ExternalDNS see only the hosted zones matching provided domain, omit to process all available hosted zones
            {{- end }}

            {{- if eq .Values.provider "cloudflare" }}
            - --provider=cloudflare
              {{- if .Values.cloudflare.proxied }}
            - --cloudflare-proxied
              {{- end }}
              {{- with .Values.cloudflare.zoneId }}
            - --zone-id-filter={{ . }}
              {{- end }}
            {{- else if eq .Values.provider "route53" }}
            - --provider=aws
              {{- with .Values.route53.zoneType }}
            - --aws-zone-type={{ . }}
              {{- end }}
              {{- with .Values.route53.zoneId }}
            - --txt-owner-id={{ . }}
              {{- end }}
            {{- end }}
          {{- if eq .Values.provider "cloudflare" }}
          env:
            - name: CF_API_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ include "external-dns.name" . }}-cloudflare-secret
                  key: cf-api-token
          {{- end}}
      securityContext:
        fsGroup: 65534 # For ExternalDNS to be able to read Kubernetes and AWS token files
