grafana:
  namespace: ""
store: filesystem  # filesystem | s3
s3:
  region: ""
  bucket: ""
  endpoint: ""
  encrypted: true
  insecure: false
  pathStyle: false
promtail:
  version: 2.1.0

prometheus:
  enable: true

tracing:
  enable: false
  dsUid: tempo
  host: tempo
  sendTraces: false
  endpoint: http://tempo:14268/api/traces
  samplerType: ratelimiting
  samplerParam: 0.2
